# Generated by Django 5.0.4 on 2024-05-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_ropa_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordatorio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
