# Generated by Django 5.0.4 on 2024-05-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_recordatorio_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ropa',
            name='image_url',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.freepik.es%2Ffotos-vectores-gratis%2Fcartoon-clothes&psig=AOvVaw2Kf7bum9RiuukKC0RMMAAb&ust=1716239052252000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCKDYrOrOmoYDFQAAAAAdAAAAABAE', max_length=2083),
        ),
    ]
