# Generated by Django 5.0.4 on 2024-05-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_ropa_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ropa',
            name='image_url',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fjohancrisst.wixsite.com%2Fluxurybrands%2Fproduct-page%2Fcamisa-gucci-negra-1&psig=AOvVaw1HiLjEceeLpkDxGVi6wq6H&ust=1716239546537000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCICUj9bQmoYDFQAAAAAdAAAAABAE', max_length=2083),
        ),
    ]
