# Generated by Django 5.0.4 on 2024-05-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_ropa_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ropa',
            name='image_url',
            field=models.CharField(default='https://static.wixstatic.com/media/6deace_63ad94bb10b44aa5b9828a67fb9e75f8~mv2.jpg/v1/fill/w_500,h_500,al_c,lg_1,q_80,enc_auto/6deace_63ad94bb10b44aa5b9828a67fb9e75f8~mv2.jpg', max_length=2083),
        ),
    ]
