# Generated by Django 5.0.4 on 2024-05-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_ropa_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(choices=[('Tienda', 'Tienda'), ('Cliente', 'Cliente')], max_length=50),
        ),
    ]
