# Generated by Django 5.0.4 on 2024-05-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_customuser_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regalo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_regalo', models.CharField(max_length=100)),
                ('contenido_regalo', models.TextField()),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_modificacion', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Nota',
        ),
    ]
